CREATE TRIGGER DEL_SUBJECT on SUBJECT
INSTEAD OF DELETE 
AS
BEGIN
DELETE FROM QUESTION WHERE IDSUBJECT IN (SELECT IDSUBJECT FROM deleted)
DELETE FROM SUBJECT WHERE IDSUBJECT IN (SELECT IDSUBJECT FROM deleted)
END