CREATE TRIGGER DEL_QUESTION on QUESTION
INSTEAD OF DELETE 
AS
BEGIN
DELETE FROM ANSWER WHERE IDQUESTION IN (SELECT IDQUESTION FROM deleted)
DELETE FROM QUESTION WHERE IDQUESTION IN (SELECT IDQUESTION FROM deleted)
END